final List<String> castasList = [
  "Alicante Bouschet",
  "Alicante Branco",
  "Alvarelhão",
  "Alvarelhão Branco",
  "Arinto (Pedernã)",
  "Aragonez (Tinta Roriz)",
  "Aramon",
  "Avesso",
  "Batoca",
  "Baga",
  "Barca",
  "Barreto",
  "Bragão",
  "Branco Especial",
  "Branco Guimarães",
  "Camarate",
  "Caramela",
  "Carrega Branco",
  "Carignan",
  "Cercial",
  "Chasselas",
  "Côdega de Larinho",
  "Diagalves",
  "Dona Branca",
  "Donzelinho Branco",
  "Donzelinho Tinto",
  "Engomada",
  "Espadeiro",
  "Fernão Pires (Maria Gomes)",
  "Folgasão",
  "Gouveio",
  "Gouveio Estimado",
  "Gouveio Real",
  "Gonçalo Pires",
  "Grand Noir",
  "Grangeal",
  "Jaen",
  "Jampal (Pinheira Branca)",
  "Lourela",
  "Malandra",
  "Malvasia Fina",
  "Malvasia Parda",
  "Malvasia Preta",
  "Malvasia Rei",
  "Marufo",
  "Melra",
  "Mondet",
  "Mourisco Branco",
  "Mourisco de Semente",
  "Nevoeira",
  "Patorra",
  "Pé Comprido",
  "Petit Bouschet",
  "Pinheira Branca",
  "Pinot Noir",
  "Praça",
  "Preto Martinho",
  "Rabigato",
  "Rabigato Franco",
  "Rabigato Moreno",
  "Rabo de Ovelha",
  "Ratinho",
  "Ricoca",
  "Roseira",
  "Rufete",
  "Samarrinho",
  "Sarigo",
  "Sercial (Esgana Cão)",
  "Síria (Roupeiro)",
  "Tália",
  "Tamarez",
  "Terrantez",
  "Tinta Aguiar",
  "Tinta Barroca",
  "Tinta Carvalha",
  "Tinta Fontes",
  "Tinta Francisca",
  "Tinta Lameira",
  "Tinta Martins",
  "Tinta Mesquita",
  "Tinta Penajóia",
  "Tinta Pereira",
  "Tinta Pomar",
  "Tinta Tabuaço",
  "Tinto Cão",
  "Tinto Sem Nome",
  "Touriga Branca",
  "Touriga Fêmea",
  "Touriga Franca",
  "Touriga Nacional",
  "Trincadeira",
  "Trigueira",
  "Valdosa",
  "Valente",
  "Varejoa",
  "Verdial Branco",
  "Viosinho",
  "Vital",
];



