// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'database/model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 3700304041740702993),
      name: 'Observation',
      lastPropertyId: const IdUid(12, 139116998772131661),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 5004875559682120053),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 8539300415548191803),
            name: 'titulo',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 8300849595602516382),
            name: 'descricao',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 3635837739136146972),
            name: 'geocode',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 3247695167272987249),
            name: 'public',
            type: 1,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 3303297332622526562),
            name: 'slugs',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 2041734917857331463),
            name: 'latitude',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 3558715404303138624),
            name: 'longitude',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(9, 4389160026631136037),
            name: 'imageFile',
            type: 30,
            flags: 0),
        ModelProperty(
            id: const IdUid(10, 8174935587505472462),
            name: 'emailController',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(11, 2212367495150789262),
            name: 'nameOfSlug',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(12, 139116998772131661),
            name: 'userGroupSlug',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(2, 8837789318023097971),
      name: 'User',
      lastPropertyId: const IdUid(10, 518715508312367429),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 4428096080477117358),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 529374394741487246),
            name: 'nome',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 6975517365595751071),
            name: 'email',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 7347330242755323143),
            name: 'username',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 215957816147837882),
            name: 'filePath',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 4487043847394684398),
            name: 'nrObs',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 2570295198363704476),
            name: 'subSlug',
            type: 30,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 4542985098358672396),
            name: 'subSlugname',
            type: 30,
            flags: 0),
        ModelProperty(
            id: const IdUid(9, 3605349020199537247),
            name: 'userGroupsName',
            type: 30,
            flags: 0),
        ModelProperty(
            id: const IdUid(10, 518715508312367429),
            name: 'userGroupsSlug',
            type: 30,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(2, 8837789318023097971),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    Observation: EntityDefinition<Observation>(
        model: _entities[0],
        toOneRelations: (Observation object) => [],
        toManyRelations: (Observation object) => {},
        getId: (Observation object) => object.id,
        setId: (Observation object, int id) {
          object.id = id;
        },
        objectToFB: (Observation object, fb.Builder fbb) {
          final tituloOffset =
              object.titulo == null ? null : fbb.writeString(object.titulo!);
          final descricaoOffset = object.descricao == null
              ? null
              : fbb.writeString(object.descricao!);
          final geocodeOffset =
              object.geocode == null ? null : fbb.writeString(object.geocode!);
          final slugsOffset =
              object.slugs == null ? null : fbb.writeString(object.slugs!);
          final imageFileOffset = object.imageFile == null
              ? null
              : fbb.writeList(object.imageFile!
                  .map(fbb.writeString)
                  .toList(growable: false));
          final emailControllerOffset = object.emailController == null
              ? null
              : fbb.writeString(object.emailController!);
          final nameOfSlugOffset = object.nameOfSlug == null
              ? null
              : fbb.writeString(object.nameOfSlug!);
          final userGroupSlugOffset = object.userGroupSlug == null
              ? null
              : fbb.writeString(object.userGroupSlug!);
          fbb.startTable(13);
          fbb.addInt64(0, object.id ?? 0);
          fbb.addOffset(1, tituloOffset);
          fbb.addOffset(2, descricaoOffset);
          fbb.addOffset(3, geocodeOffset);
          fbb.addBool(4, object.public);
          fbb.addOffset(5, slugsOffset);
          fbb.addFloat64(6, object.latitude);
          fbb.addFloat64(7, object.longitude);
          fbb.addOffset(8, imageFileOffset);
          fbb.addOffset(9, emailControllerOffset);
          fbb.addOffset(10, nameOfSlugOffset);
          fbb.addOffset(11, userGroupSlugOffset);
          fbb.finish(fbb.endTable());
          return object.id ?? 0;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Observation(
              id: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 4),
              titulo: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 6),
              descricao: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 8),
              geocode: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10),
              public: const fb.BoolReader()
                  .vTableGetNullable(buffer, rootOffset, 12),
              slugs: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 14),
              latitude: const fb.Float64Reader()
                  .vTableGetNullable(buffer, rootOffset, 16),
              longitude: const fb.Float64Reader()
                  .vTableGetNullable(buffer, rootOffset, 18),
              imageFile: const fb.ListReader<String>(fb.StringReader(asciiOptimization: true), lazy: false).vTableGetNullable(buffer, rootOffset, 20),
              emailController: const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 22),
              nameOfSlug: const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 24),
              userGroupSlug: const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 26));

          return object;
        }),
    User: EntityDefinition<User>(
        model: _entities[1],
        toOneRelations: (User object) => [],
        toManyRelations: (User object) => {},
        getId: (User object) => object.id,
        setId: (User object, int id) {
          object.id = id;
        },
        objectToFB: (User object, fb.Builder fbb) {
          final nomeOffset =
              object.nome == null ? null : fbb.writeString(object.nome!);
          final emailOffset =
              object.email == null ? null : fbb.writeString(object.email!);
          final usernameOffset = object.username == null
              ? null
              : fbb.writeString(object.username!);
          final filePathOffset = object.filePath == null
              ? null
              : fbb.writeString(object.filePath!);
          final subSlugOffset = object.subSlug == null
              ? null
              : fbb.writeList(
                  object.subSlug!.map(fbb.writeString).toList(growable: false));
          final subSlugnameOffset = object.subSlugname == null
              ? null
              : fbb.writeList(object.subSlugname!
                  .map(fbb.writeString)
                  .toList(growable: false));
          final userGroupsNameOffset = object.userGroupsName == null
              ? null
              : fbb.writeList(object.userGroupsName!
                  .map(fbb.writeString)
                  .toList(growable: false));
          final userGroupsSlugOffset = object.userGroupsSlug == null
              ? null
              : fbb.writeList(object.userGroupsSlug!
                  .map(fbb.writeString)
                  .toList(growable: false));
          fbb.startTable(11);
          fbb.addInt64(0, object.id ?? 0);
          fbb.addOffset(1, nomeOffset);
          fbb.addOffset(2, emailOffset);
          fbb.addOffset(3, usernameOffset);
          fbb.addOffset(4, filePathOffset);
          fbb.addInt64(5, object.nrObs);
          fbb.addOffset(6, subSlugOffset);
          fbb.addOffset(7, subSlugnameOffset);
          fbb.addOffset(8, userGroupsNameOffset);
          fbb.addOffset(9, userGroupsSlugOffset);
          fbb.finish(fbb.endTable());
          return object.id ?? 0;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = User(
              id: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 4),
              nome: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 6),
              email: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 8),
              username: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10),
              filePath: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 12),
              nrObs: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 14),
              subSlug: const fb.ListReader<String>(fb.StringReader(asciiOptimization: true), lazy: false)
                  .vTableGetNullable(buffer, rootOffset, 16),
              subSlugname: const fb.ListReader<String>(fb.StringReader(asciiOptimization: true), lazy: false)
                  .vTableGetNullable(buffer, rootOffset, 18),
              userGroupsName: const fb.ListReader<String>(fb.StringReader(asciiOptimization: true), lazy: false).vTableGetNullable(buffer, rootOffset, 20),
              userGroupsSlug: const fb.ListReader<String>(fb.StringReader(asciiOptimization: true), lazy: false).vTableGetNullable(buffer, rootOffset, 22));

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [Observation] entity fields to define ObjectBox queries.
class Observation_ {
  /// see [Observation.id]
  static final id =
      QueryIntegerProperty<Observation>(_entities[0].properties[0]);

  /// see [Observation.titulo]
  static final titulo =
      QueryStringProperty<Observation>(_entities[0].properties[1]);

  /// see [Observation.descricao]
  static final descricao =
      QueryStringProperty<Observation>(_entities[0].properties[2]);

  /// see [Observation.geocode]
  static final geocode =
      QueryStringProperty<Observation>(_entities[0].properties[3]);

  /// see [Observation.public]
  static final public =
      QueryBooleanProperty<Observation>(_entities[0].properties[4]);

  /// see [Observation.slugs]
  static final slugs =
      QueryStringProperty<Observation>(_entities[0].properties[5]);

  /// see [Observation.latitude]
  static final latitude =
      QueryDoubleProperty<Observation>(_entities[0].properties[6]);

  /// see [Observation.longitude]
  static final longitude =
      QueryDoubleProperty<Observation>(_entities[0].properties[7]);

  /// see [Observation.imageFile]
  static final imageFile =
      QueryStringVectorProperty<Observation>(_entities[0].properties[8]);

  /// see [Observation.emailController]
  static final emailController =
      QueryStringProperty<Observation>(_entities[0].properties[9]);

  /// see [Observation.nameOfSlug]
  static final nameOfSlug =
      QueryStringProperty<Observation>(_entities[0].properties[10]);

  /// see [Observation.userGroupSlug]
  static final userGroupSlug =
      QueryStringProperty<Observation>(_entities[0].properties[11]);
}

/// [User] entity fields to define ObjectBox queries.
class User_ {
  /// see [User.id]
  static final id = QueryIntegerProperty<User>(_entities[1].properties[0]);

  /// see [User.nome]
  static final nome = QueryStringProperty<User>(_entities[1].properties[1]);

  /// see [User.email]
  static final email = QueryStringProperty<User>(_entities[1].properties[2]);

  /// see [User.username]
  static final username = QueryStringProperty<User>(_entities[1].properties[3]);

  /// see [User.filePath]
  static final filePath = QueryStringProperty<User>(_entities[1].properties[4]);

  /// see [User.nrObs]
  static final nrObs = QueryIntegerProperty<User>(_entities[1].properties[5]);

  /// see [User.subSlug]
  static final subSlug =
      QueryStringVectorProperty<User>(_entities[1].properties[6]);

  /// see [User.subSlugname]
  static final subSlugname =
      QueryStringVectorProperty<User>(_entities[1].properties[7]);

  /// see [User.userGroupsName]
  static final userGroupsName =
      QueryStringVectorProperty<User>(_entities[1].properties[8]);

  /// see [User.userGroupsSlug]
  static final userGroupsSlug =
      QueryStringVectorProperty<User>(_entities[1].properties[9]);
}
